/**
 * Données de démonstration, miroir de supabase/seed.sql. Utilisées quand
 * aucun projet Supabase n'est configuré (variables d'environnement
 * absentes), pour que l'application reste testable sans backend réel.
 */
import type {
  EventRow,
  NewsRow,
  PartnerRow,
  AssistanceCategory,
  AssistanceItem,
  UserProfile,
} from "@/types/database";

const inDays = (d: number) => new Date(Date.now() + d * 86_400_000).toISOString();

export const demoEvents: EventRow[] = [
  {
    id: "evt-1",
    title: "Soirée d'intégration BDE",
    description:
      "La soirée de rentrée qui rassemble tous les campus d'Aix. Musique, foodtrucks et animations toute la soirée.",
    category_id: 1,
    cover_url: null,
    gallery: [],
    starts_at: inDays(2),
    ends_at: null,
    address: "Le Central, Aix-en-Provence",
    lat: 43.5297,
    lng: 5.4474,
    is_free: true,
    price_cents: 0,
    capacity: 400,
    seats_taken: 128,
    organizer_name: "BDE Aix",
    status: "published",
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-2",
    title: "Conférence IA & Emploi",
    description:
      "Rencontre avec des professionnels de l'IA pour préparer votre insertion professionnelle. Tables rondes et networking.",
    category_id: 5,
    cover_url: null,
    gallery: [],
    starts_at: inDays(5),
    ends_at: null,
    address: "Amphi A, Campus Schuman",
    lat: 43.5223,
    lng: 5.4526,
    is_free: true,
    price_cents: 0,
    capacity: 200,
    seats_taken: 64,
    organizer_name: "Junior Entreprise IAE",
    status: "published",
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-3",
    title: "Tournoi de foot inter-campus",
    description:
      "Tournoi amical entre toutes les facs d'Aix-Marseille. Inscription par équipe de 7.",
    category_id: 3,
    cover_url: null,
    gallery: [],
    starts_at: inDays(7),
    ends_at: null,
    address: "Stade universitaire, Aix-en-Provence",
    lat: 43.5162,
    lng: 5.4408,
    is_free: false,
    price_cents: 500,
    capacity: 150,
    seats_taken: 96,
    organizer_name: "SUAPS Aix-Marseille",
    status: "published",
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-4",
    title: "Expo photo : Aix vue par ses étudiants",
    description:
      "Vernissage de l'exposition annuelle des clubs photo des campus aixois.",
    category_id: 2,
    cover_url: null,
    gallery: [],
    starts_at: inDays(9),
    ends_at: null,
    address: "Galerie du Cours, Aix-en-Provence",
    lat: 43.5275,
    lng: 5.4491,
    is_free: true,
    price_cents: 0,
    capacity: 120,
    seats_taken: 31,
    organizer_name: "Club Photo Aix",
    status: "published",
    created_at: new Date().toISOString(),
  },
];

export const eventCategories = [
  { id: 1, slug: "soiree", label: "Soirées", icon: "PartyPopper" },
  { id: 2, slug: "culture", label: "Culture", icon: "Palette" },
  { id: 3, slug: "sport", label: "Sport", icon: "Trophy" },
  { id: 4, slug: "association", label: "Associations", icon: "Users" },
  { id: 5, slug: "conference", label: "Conférences", icon: "Presentation" },
];

export const demoNews: NewsRow[] = [
  {
    id: "news-1",
    title: "Rentrée 2026 : les nouveautés du campus",
    body: "Nouveaux horaires de bibliothèque, travaux terminés au CROUS, et bien plus.",
    source: "university",
    cover_url: null,
    published_at: inDays(-1),
  },
  {
    id: "news-2",
    title: "Le BDE lance sa nouvelle carte de réductions",
    body: "Plus de 40 partenaires en centre-ville d'Aix acceptent désormais la carte BDE.",
    source: "bde",
    cover_url: null,
    published_at: inDays(-2),
  },
  {
    id: "news-3",
    title: "Aix-en-Provence renforce les navettes de nuit",
    body: "La ville étend le réseau Aix en Bus le week-end pour sécuriser les trajets nocturnes.",
    source: "city",
    cover_url: null,
    published_at: inDays(-4),
  },
];

export const demoPartners: PartnerRow[] = [
  {
    id: "partner-1",
    name: "Pizzeria Bella Vita",
    category: "restaurant",
    description: "Pizzas au feu de bois en centre-ville.",
    discount_label: "-15% sur présentation de la carte étudiante",
    logo_url: null,
    address: "Cours Mirabeau, Aix-en-Provence",
  },
  {
    id: "partner-2",
    name: "Librairie Campus",
    category: "commerce",
    description: "Livres universitaires neufs et d'occasion.",
    discount_label: "-10% sur les manuels",
    logo_url: null,
    address: "Rue Espariat, Aix-en-Provence",
  },
];

export const assistanceCategories: AssistanceCategory[] = [
  { id: 1, slug: "applications-utiles", label: "Applications utiles", icon: "Smartphone", color: "blue", sort_order: 1 },
  { id: 2, slug: "aides-financieres", label: "Aides financières", icon: "Wallet", color: "green", sort_order: 2 },
  { id: 3, slug: "sante-bien-etre", label: "Santé & Bien-être", icon: "HeartPulse", color: "pink", sort_order: 3 },
  { id: 4, slug: "aide-alimentaire", label: "Aide alimentaire", icon: "UtensilsCrossed", color: "orange", sort_order: 4 },
  { id: 5, slug: "urgences", label: "Numéros d'urgence", icon: "Siren", color: "red", sort_order: 5 },
  { id: 6, slug: "logement", label: "Logement étudiant", icon: "Home", color: "indigo", sort_order: 6 },
  { id: 7, slug: "administratif", label: "Assistance administrative", icon: "Scale", color: "slate", sort_order: 7 },
  { id: 8, slug: "transport", label: "Transport", icon: "Bus", color: "cyan", sort_order: 8 },
  { id: 9, slug: "universites", label: "Universités", icon: "GraduationCap", color: "violet", sort_order: 9 },
  { id: 10, slug: "plans-campus", label: "Plans du campus", icon: "MapPinned", color: "teal", sort_order: 10 },
];

export const demoAssistanceItems: AssistanceItem[] = [
  {
    id: "app-izly",
    category_id: 1,
    type: "app",
    title: "Izly",
    subtitle: "Paiement CROUS",
    description: "Payez vos repas au RU et rechargez votre compte étudiant.",
    logo_url: null,
    phone: null,
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: "https://izly.izly.fr",
    download_ios_url: "https://apps.apple.com/app/izly",
    download_android_url: "https://play.google.com/store/apps/details?id=fr.izly",
    address: null,
    opening_hours: null,
    sort_order: 1,
  },
  {
    id: "app-caf",
    category_id: 1,
    type: "app",
    title: "CAF — Mon Compte",
    subtitle: "Aides au logement",
    description: "Simulez et suivez vos APL directement depuis l'app.",
    logo_url: null,
    phone: null,
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: "https://www.caf.fr",
    download_ios_url: "https://apps.apple.com/app/caf-mon-compte",
    download_android_url: "https://play.google.com/store/apps/details?id=fr.caf.mobile",
    address: null,
    opening_hours: null,
    sort_order: 2,
  },
  {
    id: "app-doctolib",
    category_id: 1,
    type: "app",
    title: "Doctolib",
    subtitle: "Rendez-vous médicaux",
    description: "Prenez rendez-vous chez un médecin, dentiste ou psychologue.",
    logo_url: null,
    phone: null,
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: "https://www.doctolib.fr",
    download_ios_url: "https://apps.apple.com/app/doctolib",
    download_android_url: "https://play.google.com/store/apps/details?id=com.doctolib.patient",
    address: null,
    opening_hours: null,
    sort_order: 3,
  },
  {
    id: "app-sncf",
    category_id: 1,
    type: "app",
    title: "SNCF Connect",
    subtitle: "Billets de train",
    description: "Achetez vos billets et profitez de la carte Avantage Jeune.",
    logo_url: null,
    phone: null,
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: "https://www.sncf-connect.com",
    download_ios_url: "https://apps.apple.com/app/sncf-connect",
    download_android_url:
      "https://play.google.com/store/apps/details?id=com.vsct.vsc.mobile.izicore",
    address: null,
    opening_hours: null,
    sort_order: 4,
  },
  {
    id: "app-france-identite",
    category_id: 1,
    type: "app",
    title: "France Identité",
    subtitle: "Papiers d'identité",
    description: "Votre identité numérique officielle et sécurisée.",
    logo_url: null,
    phone: null,
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: "https://france-identite.gouv.fr",
    download_ios_url: "https://apps.apple.com/app/france-identite",
    download_android_url:
      "https://play.google.com/store/apps/details?id=fr.gouv.franceidentite",
    address: null,
    opening_hours: null,
    sort_order: 5,
  },
  {
    id: "urg-samu",
    category_id: 5,
    type: "contact",
    title: "SAMU",
    subtitle: "Urgence médicale",
    description: null,
    logo_url: null,
    phone: "15",
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: null,
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 1,
  },
  {
    id: "urg-police",
    category_id: 5,
    type: "contact",
    title: "Police / Gendarmerie",
    subtitle: "Urgence sécurité",
    description: null,
    logo_url: null,
    phone: "17",
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: null,
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 2,
  },
  {
    id: "urg-pompiers",
    category_id: 5,
    type: "contact",
    title: "Pompiers",
    subtitle: "Urgence incendie / secours",
    description: null,
    logo_url: null,
    phone: "18",
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: null,
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 3,
  },
  {
    id: "urg-112",
    category_id: 5,
    type: "contact",
    title: "Numéro d'urgence européen",
    subtitle: "Toutes urgences (mobile, UE)",
    description: null,
    logo_url: null,
    phone: "112",
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: null,
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 4,
  },
  {
    id: "urg-violences-femmes",
    category_id: 5,
    type: "contact",
    title: "Violences Femmes Info",
    subtitle: "Violences conjugales, sexistes",
    description: null,
    logo_url: null,
    phone: "3919",
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: null,
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 5,
  },
  {
    id: "urg-3114",
    category_id: 5,
    type: "contact",
    title: "3114 — Prévention suicide",
    subtitle: "Écoute et prévention du suicide, 24h/24",
    description: null,
    logo_url: null,
    phone: "3114",
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: null,
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 6,
  },
  {
    id: "urg-enfance",
    category_id: 5,
    type: "contact",
    title: "Enfance en danger",
    subtitle: "Signalement, écoute mineurs",
    description: null,
    logo_url: null,
    phone: "119",
    amount_label: null,
    conditions: null,
    documents: [],
    faq: [],
    official_url: null,
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 7,
  },
  {
    id: "aide-crous",
    category_id: 2,
    type: "aide",
    title: "Bourse CROUS",
    subtitle: "Sur critères sociaux",
    description: null,
    logo_url: null,
    phone: null,
    amount_label: "Jusqu'à ~600€/mois selon échelon",
    conditions: "Selon revenus du foyer, calculée via le Dossier Social Étudiant (DSE)",
    documents: [],
    faq: [],
    official_url: "https://www.crous-aix-marseille.fr",
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 1,
  },
  {
    id: "aide-apl",
    category_id: 2,
    type: "aide",
    title: "APL — Aide au logement",
    subtitle: "Versée par la CAF",
    description: null,
    logo_url: null,
    phone: null,
    amount_label: "Variable selon loyer et ville",
    conditions: "Simulation obligatoire, dossier CAF en ligne",
    documents: [],
    faq: [],
    official_url: "https://www.caf.fr",
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 2,
  },
  {
    id: "aide-urgence",
    category_id: 2,
    type: "aide",
    title: "Fonds d'urgence CROUS",
    subtitle: "Aide ponctuelle",
    description: null,
    logo_url: null,
    phone: null,
    amount_label: "Montant évalué au cas par cas",
    conditions: "Difficulté financière soudaine et imprévue",
    documents: [],
    faq: [],
    official_url: "https://www.crous-aix-marseille.fr",
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 3,
  },
  {
    id: "aide-region-sud",
    category_id: 2,
    type: "aide",
    title: "Aides Région Sud",
    subtitle: "Mobilité, formation",
    description: null,
    logo_url: null,
    phone: null,
    amount_label: "Variable selon dispositif",
    conditions: "Étudiants inscrits en région Sud",
    documents: [],
    faq: [],
    official_url: "https://www.maregionsud.fr",
    download_ios_url: null,
    download_android_url: null,
    address: null,
    opening_hours: null,
    sort_order: 4,
  },
];

export const demoProfile: UserProfile = {
  id: "demo-user",
  full_name: "Camille Martin",
  avatar_url: null,
  university: "Aix-Marseille Université",
  field_of_study: "Licence Informatique",
  campus: "Campus Schuman",
  city: "Aix-en-Provence",
  push_subscription: null,
  created_at: new Date().toISOString(),
};
